<a href="https://colab.research.google.com/github/yeeshukanda-source/AAI2025/blob/main/Group_Work_%7C_Ad_Optimization_Agent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import random
from datetime import datetime, timedelta

random.seed(42)

data = []
start_date = datetime(2026, 10, 1)

# Create 21 days of mock advertising data
for day in range(21):
    date = (start_date + timedelta(days=day)).strftime("%Y-%m-%d")

    # Search - generally strongest conversions
    data.append([
        date, "Search",
        random.randint(90, 110),
        random.randint(4500, 6000),
        random.randint(220, 320),
        random.randint(18, 28)
    ])

    # Social - medium performance
    data.append([
        date, "Social",
        random.randint(90, 110),
        random.randint(6000, 8000),
        random.randint(230, 330),
        random.randint(12, 22)
    ])

    # Display - generally lower conversions
    data.append([
        date, "Display",
        random.randint(90, 110),
        random.randint(8000, 11000),
        random.randint(180, 280),
        random.randint(6, 15)
    ])

df = pd.DataFrame(
    data,
    columns=[
        "date",
        "channel",
        "spend",
        "impressions",
        "clicks",
        "conversions"
    ]
)

# Save the dataset
df.to_csv("ad_performance.csv", index=False)

print("CSV created successfully!")
print("Number of rows:", len(df))
print(df.head(10))

CSV created successfully!
Number of rows: 63
         date  channel  spend  impressions  clicks  conversions
0  2026-10-01   Search    110         4728     223           22
1  2026-10-01   Social     97         6457     247           13
2  2026-10-01  Display    107         8356     255           12
3  2026-10-02   Search     91         4561     231           21
4  2026-10-02   Social     97         7034     307           12
5  2026-10-02  Display    107         8814     271           14
6  2026-10-03   Search    103         4951     277           27
7  2026-10-03   Social     98         7657     230           14
8  2026-10-03  Display    103         9393     215            8
9  2026-10-04   Search     96         5189     233           19

In [3]:
import pandas as pd

df = pd.read_csv("ad_performance.csv")

print(df.head())

         date  channel  spend  impressions  clicks  conversions
0  2026-10-01   Search    110         4728     223           22
1  2026-10-01   Social     97         6457     247           13
2  2026-10-01  Display    107         8356     255           12
3  2026-10-02   Search     91         4561     231           21
4  2026-10-02   Social     97         7034     307           12

In [4]:
# Calculate advertising performance metrics

df["CTR"] = df["clicks"] / df["impressions"]
df["CVR"] = df["conversions"] / df["clicks"]
df["CPA"] = df["spend"] / df["conversions"]

# Show results
print("Performance Metrics:")
display(df.head(10))

Performance Metrics:

,date,channel,spend,impressions,clicks,conversions,CTR,CVR,CPA
0,2026-10-01,Search,110,4728,223,22,0.047166,0.098655,5.000000
1,2026-10-01,Social,97,6457,247,13,0.038253,0.052632,7.461538
2,2026-10-01,Display,107,8356,255,12,0.030517,0.047059,8.916667
3,2026-10-02,Search,91,4561,231,21,0.050647,0.090909,4.333333
4,2026-10-02,Social,97,7034,307,12,0.043645,0.039088,8.083333
5,2026-10-02,Display,107,8814,271,14,0.030747,0.051661,7.642857
6,2026-10-03,Search,103,4951,277,27,0.055948,0.097473,3.814815
7,2026-10-03,Social,98,7657,230,14,0.030038,0.060870,7.000000
8,2026-10-03,Display,103,9393,215,8,0.022889,0.037209,12.875000
9,2026-10-04,Search,96,5189,233,19,0.044903,0.081545,5.052632

In [5]:
# Summarize performance by channel

summary = df.groupby("channel").agg(
    Spend=("spend", "sum"),
    Impressions=("impressions", "sum"),
    Clicks=("clicks", "sum"),
    Conversions=("conversions", "sum")
)

summary["CTR"] = summary["Clicks"] / summary["Impressions"]
summary["CVR"] = summary["Conversions"] / summary["Clicks"]
summary["CPA"] = summary["Spend"] / summary["Conversions"]

summary = summary.sort_values("CVR", ascending=False)

print("Channel Performance Summary:")
display(summary.round(4))

Channel Performance Summary:

         Spend  Impressions  Clicks  Conversions     CTR     CVR     CPA
channel
Search    2120       110785    5461          455  0.0493  0.0833  4.6593
Social    2108       147169    5695          340  0.0387  0.0597  6.2000
Display   2147       201162    4881          222  0.0243  0.0455  9.6712

In [6]:
# Step 4: Recommend new daily budget allocation

total_budget = 300

# Start with an equal split
current_budget = {
    "Search": 100,
    "Social": 100,
    "Display": 100
}

# Maximum change allowed = 20%
max_change = 0.20

# Recommended allocation based on channel performance
new_budget = {
    "Search": 120,   # Increase by 20%
    "Social": 100,   # Keep the same
    "Display": 80    # Decrease by 20%
}

print("=== AD OPTIMIZATION AGENT ===")
print(f"Total Daily Budget: ${total_budget}")
print()

for channel in ["Search", "Social", "Display"]:
    old = current_budget[channel]
    new = new_budget[channel]
    change = ((new - old) / old) * 100

    print(f"{channel}")
    print(f"Previous Budget: ${old}")
    print(f"New Budget: ${new}")
    print(f"Change: {change:.0f}%")

    if channel == "Search":
        print("Reason: Increased because Search has the highest CVR and lowest CPA.")
    elif channel == "Social":
        print("Reason: Kept stable because Social has moderate performance.")
    else:
        print("Reason: Reduced because Display has the lowest CVR and highest CPA.")

    print()

print(f"New Total Budget: ${sum(new_budget.values())}")

=== AD OPTIMIZATION AGENT ===
Total Daily Budget: $300

Search
Previous Budget: $100
New Budget: $120
Change: 20%
Reason: Increased because Search has the highest CVR and lowest CPA.

Social
Previous Budget: $100
New Budget: $100
Change: 0%
Reason: Kept stable because Social has moderate performance.

Display
Previous Budget: $100
New Budget: $80
Change: -20%
Reason: Reduced because Display has the lowest CVR and highest CPA.

New Total Budget: $300

In [7]:
# Step 5: Automated Ad Optimization Agent

# Starting equal budget
current_budget = {
    "Search": 100,
    "Social": 100,
    "Display": 100
}

# Automatically rank channels using CVR
ranked_channels = summary.sort_values("CVR", ascending=False)

best_channel = ranked_channels.index[0]
middle_channel = ranked_channels.index[1]
weakest_channel = ranked_channels.index[2]

# Apply maximum 20% change
new_budget = current_budget.copy()

new_budget[best_channel] = current_budget[best_channel] * 1.20
new_budget[middle_channel] = current_budget[middle_channel]
new_budget[weakest_channel] = current_budget[weakest_channel] * 0.80

print("=== AUTOMATED AD OPTIMIZATION AGENT ===")
print()

print("Best Channel:", best_channel)
print("Middle Channel:", middle_channel)
print("Weakest Channel:", weakest_channel)
print()

for channel in current_budget:

    old = current_budget[channel]
    new = new_budget[channel]
    change = ((new - old) / old) * 100

    print(channel)
    print(f"Previous Budget: ${old:.2f}")
    print(f"Recommended Budget: ${new:.2f}")
    print(f"Change: {change:.0f}%")

    if channel == best_channel:
        print(
            f"Reason: Increased because {channel} has the "
            "strongest conversion performance."
        )

    elif channel == weakest_channel:
        print(
            f"Reason: Reduced because {channel} has the "
            "weakest conversion performance."
        )

    else:
        print(
            f"Reason: Kept stable because {channel} has "
            "middle-level performance."
        )

    print()

print(f"Total Recommended Budget: ${sum(new_budget.values()):.2f}")

# Guardrail check
if abs(sum(new_budget.values()) - 300) < 0.01:
    print("Guardrail Check: PASSED - Total budget remains $300.")
else:
    print("Guardrail Check: FAILED")

=== AUTOMATED AD OPTIMIZATION AGENT ===

Best Channel: Search
Middle Channel: Social
Weakest Channel: Display

Search
Previous Budget: $100.00
Recommended Budget: $120.00
Change: 20%
Reason: Increased because Search has the strongest conversion performance.

Social
Previous Budget: $100.00
Recommended Budget: $100.00
Change: 0%
Reason: Kept stable because Social has middle-level performance.

Display
Previous Budget: $100.00
Recommended Budget: $80.00
Change: -20%
Reason: Reduced because Display has the weakest conversion performance.

Total Recommended Budget: $300.00
Guardrail Check: PASSED - Total budget remains $300.

In [13]:
# Step 6: Create a decision log

decision_log = []

for channel in current_budget:
    old = current_budget[channel]
    new = new_budget[channel]
    change = ((new - old) / old) * 100

    if channel == best_channel:
        reason = f"{channel} increased because it had the strongest CVR performance."
    elif channel == weakest_channel:
        reason = f"{channel} decreased because it had the weakest CVR performance."
    else:
        reason = f"{channel} stayed the same because it had middle-level performance."

    decision_log.append({
        "Date": "2026-10-26",
        "Channel": channel,
        "Previous Budget": old,
        "New Budget": new,
        "Change (%)": change,
        "Metric Used": "CVR",
        "Reason": reason
    })

log_df = pd.DataFrame(decision_log)

print("=== DECISION LOG ===")
display(log_df)

# Save the log as a CSV file
log_df.to_csv("decision_log.csv", index=False)

print("Decision log saved as decision_log.csv")

=== DECISION LOG ===

,Date,Channel,Previous Budget,New Budget,Change (%),Metric Used,Reason
0,2026-10-26,Search,100,120.0,20.0,CVR,Search increased because it had the strongest ...
1,2026-10-26,Social,100,100.0,0.0,CVR,Social stayed the same because it had middle-l...
2,2026-10-26,Display,100,80.0,-20.0,CVR,Display decreased because it had the weakest C...

Decision log saved as decision_log.csv

In [9]:
# Step 7: Minimum budget floor guardrail

minimum_budget = 50
total_budget = 300

print("=== GUARDRAIL CHECKS ===")

# Check minimum budget
floor_passed = True

for channel, budget in new_budget.items():
    if budget < minimum_budget:
        floor_passed = False
        print(f"FAILED: {channel} is below the ${minimum_budget} minimum.")
    else:
        print(f"PASSED: {channel} budget ${budget:.2f} is above the minimum.")

# Check total budget
if abs(sum(new_budget.values()) - total_budget) < 0.01:
    print(f"PASSED: Total budget remains ${total_budget}.")
else:
    print("FAILED: Total budget changed.")

# Check maximum 20% daily change
change_passed = True

for channel in current_budget:
    percent_change = abs(
        (new_budget[channel] - current_budget[channel])
        / current_budget[channel]
    )

    if percent_change > 0.20 + 1e-9:
        change_passed = False
        print(f"FAILED: {channel} changed by more than 20%.")

if change_passed:
    print("PASSED: No channel changed by more than 20%.")

# Final result
if floor_passed and change_passed and abs(sum(new_budget.values()) - total_budget) < 0.01:
    print("\nALL GUARDRAILS PASSED.")

=== GUARDRAIL CHECKS ===
PASSED: Search budget $120.00 is above the minimum.
PASSED: Social budget $100.00 is above the minimum.
PASSED: Display budget $80.00 is above the minimum.
PASSED: Total budget remains $300.
PASSED: No channel changed by more than 20%.

ALL GUARDRAILS PASSED.

In [10]:
# Step 8: Compare equal-split baseline vs optimized budget

# Calculate historical conversions per dollar
summary["Conversions_Per_Dollar"] = (
    summary["Conversions"] / summary["Spend"]
)

# Baseline: equal $100 allocation
baseline_budget = {
    "Search": 100,
    "Social": 100,
    "Display": 100
}

# Agent recommendation from previous step
optimized_budget = new_budget

baseline_conversions = 0
optimized_conversions = 0

for channel in baseline_budget:
    efficiency = summary.loc[channel, "Conversions_Per_Dollar"]

    baseline_conversions += (
        baseline_budget[channel] * efficiency
    )

    optimized_conversions += (
        optimized_budget[channel] * efficiency
    )

improvement = optimized_conversions - baseline_conversions
improvement_percent = (
    improvement / baseline_conversions
) * 100

baseline_cpa = 300 / baseline_conversions
optimized_cpa = 300 / optimized_conversions

print("=== BASELINE VS OPTIMIZED EVALUATION ===")
print()

print("Equal-Split Baseline:")
print(f"Expected Conversions: {baseline_conversions:.2f}")
print(f"Expected CPA: ${baseline_cpa:.2f}")

print()

print("Agent Optimized Budget:")
print(f"Expected Conversions: {optimized_conversions:.2f}")
print(f"Expected CPA: ${optimized_cpa:.2f}")

print()

print(f"Conversion Improvement: {improvement:.2f}")
print(f"Percentage Improvement: {improvement_percent:.2f}%")

=== BASELINE VS OPTIMIZED EVALUATION ===

Equal-Split Baseline:
Expected Conversions: 47.93
Expected CPA: $6.26

Agent Optimized Budget:
Expected Conversions: 50.16
Expected CPA: $5.98

Conversion Improvement: 2.22
Percentage Improvement: 4.64%

In [11]:
# Step 9: Final results summary

print("=== FINAL AGENT RESULTS ===")
print("Optimization Goal: Maximize conversions")
print("Total Daily Budget: $300")
print()

print("Recommended Budget:")
print("Search:  $120")
print("Social:  $100")
print("Display: $80")
print()

print("Baseline Expected Conversions: 47.93")
print("Optimized Expected Conversions: 50.16")
print("Improvement: 4.64%")
print()

print("Baseline CPA: $6.26")
print("Optimized CPA: $5.98")
print()

print("All guardrails passed:")
print("- Maximum daily change: 20%")
print("- Minimum budget floor: $50")
print("- Total budget maintained: $300")
print("- Every decision includes a reason")

=== FINAL AGENT RESULTS ===
Optimization Goal: Maximize conversions
Total Daily Budget: $300

Recommended Budget:
Search:  $120
Social:  $100
Display: $80

Baseline Expected Conversions: 47.93
Optimized Expected Conversions: 50.16
Improvement: 4.64%

Baseline CPA: $6.26
Optimized CPA: $5.98

All guardrails passed:
- Maximum daily change: 20%
- Minimum budget floor: $50
- Total budget maintained: $300
- Every decision includes a reason

In [12]:
# Step 10: System Prompt for the Ad Optimization Agent

SYSTEM_PROMPT = """
You are an Ad Optimization Agent.

Your role is to analyze advertising performance across
Search, Social, and Display channels and recommend how to
allocate the daily advertising budget.

GOAL:
Maximize conversions while keeping CPA low.

INPUTS:
- Spend
- Impressions
- Clicks
- Conversions
- Total daily budget

RULES:
1. Use CVR as the main performance metric.
2. Use CPA as a supporting metric.
3. Never exceed the total daily budget.
4. Do not change a channel's budget by more than 20% per day.
5. Maintain at least $50 for every channel.
6. Never completely remove a channel from the allocation.
7. Provide a clear reason for every budget decision.
8. Use only mock or anonymized advertising data.
9. Do not make discriminatory or personal targeting decisions.
10. Keep explanations factual, neutral, and professional.

OUTPUT:
Provide the recommended budget for Search, Social, and Display
and explain the reason for each change.
"""

print(SYSTEM_PROMPT)

You are an Ad Optimization Agent.

Your role is to analyze advertising performance across
Search, Social, and Display channels and recommend how to
allocate the daily advertising budget.

GOAL:
Maximize conversions while keeping CPA low.

INPUTS:
- Spend
- Impressions
- Clicks
- Conversions
- Total daily budget

RULES:
1. Use CVR as the main performance metric.
2. Use CPA as a supporting metric.
3. Never exceed the total daily budget.
4. Do not change a channel's budget by more than 20% per day.
5. Maintain at least $50 for every channel.
6. Never completely remove a channel from the allocation.
7. Provide a clear reason for every budget decision.
8. Use only mock or anonymized advertising data.
9. Do not make discriminatory or personal targeting decisions.
10. Keep explanations factual, neutral, and professional.

OUTPUT:
Provide the recommended budget for Search, Social, and Display
and explain the reason for each change.